{"uid":"935bb2417ddfc0f1","name":"[LoginEmployee] Incorrect phone number","fullName":"TestRunner/AuthSuite/Test_Auth_LoginEmployee1","historyId":"8bd5408b6ad169dc24723c7496052f9c","time":{"start":1728203957118,"stop":1728203957125,"duration":7},"status":"failed","statusMessage":"\n\nmock: Unexpected Method Call\n-----------------------------\n\nGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"7n8c8937d38d73\"}\n\nThe closest call I have is: \n\nGetByPhone(context.todoCtx,*dto.LoginEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.LoginEmployeeRequest{PhoneNumber:\"7n8c8937d38d73\", Password:\"21e12\"}\n\n\nDiff: 0: PASS:  (context.todoCtx=context.TODO) == (context.todoCtx=context.TODO)\n\t1: FAIL:  (*dto.GetEmployeeRequest=&{7n8c8937d38d73}) != (*dto.LoginEmployeeRequest=&{7n8c8937d38d73 21e12})","statusTrace":"\n\n\nmock: Unexpected Method Call\n-----------------------------\n\nGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"7n8c8937d38d73\"}\n\nThe closest call I have is: \n\nGetByPhone(context.todoCtx,*dto.LoginEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.LoginEmployeeRequest{PhoneNumber:\"7n8c8937d38d73\", Password:\"21e12\"}\n\n\nDiff: 0: PASS:  (context.todoCtx=context.TODO) == (context.todoCtx=context.TODO)\n\t1: FAIL:  (*dto.GetEmployeeRequest=&{7n8c8937d38d73}) != (*dto.LoginEmployeeRequest=&{7n8c8937d38d73 21e12})","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"\n\nmock: Unexpected Method Call\n-----------------------------\n\nGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"7n8c8937d38d73\"}\n\nThe closest call I have is: \n\nGetByPhone(context.todoCtx,*dto.LoginEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.LoginEmployeeRequest{PhoneNumber:\"7n8c8937d38d73\", Password:\"21e12\"}\n\n\nDiff: 0: PASS:  (context.todoCtx=context.TODO) == (context.todoCtx=context.TODO)\n\t1: FAIL:  (*dto.GetEmployeeRequest=&{7n8c8937d38d73}) != (*dto.LoginEmployeeRequest=&{7n8c8937d38d73 21e12})","statusTrace":"\n\n\nmock: Unexpected Method Call\n-----------------------------\n\nGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"7n8c8937d38d73\"}\n\nThe closest call I have is: \n\nGetByPhone(context.todoCtx,*dto.LoginEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.LoginEmployeeRequest{PhoneNumber:\"7n8c8937d38d73\", Password:\"21e12\"}\n\n\nDiff: 0: PASS:  (context.todoCtx=context.TODO) == (context.todoCtx=context.TODO)\n\t1: FAIL:  (*dto.GetEmployeeRequest=&{7n8c8937d38d73}) != (*dto.LoginEmployeeRequest=&{7n8c8937d38d73 21e12})","steps":[{"name":"Incorrect phone number","time":{"start":1728203957124,"stop":1728203957125,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"ctx","value":"context.TODO"},{"name":"request","value":"&{PhoneNumber:7n8c8937d38d73 Password:21e12}"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":0,"hasContent":true},"afterStages":[],"labels":[{"name":"language","value":"go1.23.1"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"fv-az847-791"},{"name":"thread","value":"TestRunner/AuthSuite/Test_Auth_LoginEmployee1"},{"name":"suite","value":"AuthSuite"},{"name":"package","value":"course/internal/service_test.TestRunner"},{"name":"tag","value":"auth"},{"name":"tag","value":"login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":2,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"4c469ae6f86eb573","reportUrl":"https://pstpn.github.io/Testing/14//#testresult/4c469ae6f86eb573","status":"failed","statusDetails":"\nassert: mock: I don't know what to return because the method call was unexpected.\n\tEither do Mock.On(\"GetByPhone\").Return(...) first, or remove the GetByPhone() call.\n\tThis method was unexpected:\n\t\tGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"7n8c8937d38d73\"}\n\tat: [/home/runner/work/Testing/Testing/internal/storage/mocks/EmployeeStorage.go:69 /home/runner/work/Testing/Testing/internal/service/auth.go:117 /home/runner/work/Testing/Testing/internal/service/auth_test.go:78 /home/runner/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.32/core/common/steps.go:27 /home/runner/work/Testing/Testing/internal/service/auth_test.go:59]","time":{"start":1728203504141,"stop":1728203504154,"duration":13}}]},"tags":["auth","login"]},"source":"935bb2417ddfc0f1.json","parameterValues":[]}