{"uid":"3d793a1df9d4f658","name":"[LoginEmployee] Incorrect password","fullName":"TestRunner/AuthSuite/Test_Auth_LoginEmployee2","historyId":"5f174d7f41d8e1f2e72e73ee55eacfc7","time":{"start":1728203504141,"stop":1728203504156,"duration":15},"status":"failed","statusMessage":"\nassert: mock: I don't know what to return because the method call was unexpected.\n\tEither do Mock.On(\"GetByPhone\").Return(...) first, or remove the GetByPhone() call.\n\tThis method was unexpected:\n\t\tGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"123\"}\n\tat: [/home/runner/work/Testing/Testing/internal/storage/mocks/EmployeeStorage.go:69 /home/runner/work/Testing/Testing/internal/service/auth.go:117 /home/runner/work/Testing/Testing/internal/service/auth_test.go:119 /home/runner/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.32/core/common/steps.go:27 /home/runner/work/Testing/Testing/internal/service/auth_test.go:89]","statusTrace":"\n\nassert: mock: I don't know what to return because the method call was unexpected.\n\tEither do Mock.On(\"GetByPhone\").Return(...) first, or remove the GetByPhone() call.\n\tThis method was unexpected:\n\t\tGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"123\"}\n\tat: [/home/runner/work/Testing/Testing/internal/storage/mocks/EmployeeStorage.go:69 /home/runner/work/Testing/Testing/internal/service/auth.go:117 /home/runner/work/Testing/Testing/internal/service/auth_test.go:119 /home/runner/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.32/core/common/steps.go:27 /home/runner/work/Testing/Testing/internal/service/auth_test.go:89]","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"\nassert: mock: I don't know what to return because the method call was unexpected.\n\tEither do Mock.On(\"GetByPhone\").Return(...) first, or remove the GetByPhone() call.\n\tThis method was unexpected:\n\t\tGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"123\"}\n\tat: [/home/runner/work/Testing/Testing/internal/storage/mocks/EmployeeStorage.go:69 /home/runner/work/Testing/Testing/internal/service/auth.go:117 /home/runner/work/Testing/Testing/internal/service/auth_test.go:119 /home/runner/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.32/core/common/steps.go:27 /home/runner/work/Testing/Testing/internal/service/auth_test.go:89]","statusTrace":"\n\nassert: mock: I don't know what to return because the method call was unexpected.\n\tEither do Mock.On(\"GetByPhone\").Return(...) first, or remove the GetByPhone() call.\n\tThis method was unexpected:\n\t\tGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"123\"}\n\tat: [/home/runner/work/Testing/Testing/internal/storage/mocks/EmployeeStorage.go:69 /home/runner/work/Testing/Testing/internal/service/auth.go:117 /home/runner/work/Testing/Testing/internal/service/auth_test.go:119 /home/runner/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.32/core/common/steps.go:27 /home/runner/work/Testing/Testing/internal/service/auth_test.go:89]","steps":[{"name":"Incorrect password","time":{"start":1728203504155,"stop":1728203504156,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"ctx","value":"context.TODO"},{"name":"request","value":"&{PhoneNumber:123 Password:89t3n82rdjy437dr}"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":0,"hasContent":true},"afterStages":[],"labels":[{"name":"language","value":"go1.23.1"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"fv-az1759-555"},{"name":"thread","value":"TestRunner/AuthSuite/Test_Auth_LoginEmployee2"},{"name":"suite","value":"AuthSuite"},{"name":"package","value":"course/internal/service_test.TestRunner"},{"name":"tag","value":"auth"},{"name":"tag","value":"login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":["auth","login"]},"source":"3d793a1df9d4f658.json","parameterValues":[]}