{"uid":"4c469ae6f86eb573","name":"[LoginEmployee] Incorrect phone number","fullName":"TestRunner/AuthSuite/Test_Auth_LoginEmployee1","historyId":"8bd5408b6ad169dc24723c7496052f9c","time":{"start":1728203504141,"stop":1728203504154,"duration":13},"status":"failed","statusMessage":"\nassert: mock: I don't know what to return because the method call was unexpected.\n\tEither do Mock.On(\"GetByPhone\").Return(...) first, or remove the GetByPhone() call.\n\tThis method was unexpected:\n\t\tGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"7n8c8937d38d73\"}\n\tat: [/home/runner/work/Testing/Testing/internal/storage/mocks/EmployeeStorage.go:69 /home/runner/work/Testing/Testing/internal/service/auth.go:117 /home/runner/work/Testing/Testing/internal/service/auth_test.go:78 /home/runner/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.32/core/common/steps.go:27 /home/runner/work/Testing/Testing/internal/service/auth_test.go:59]","statusTrace":"\n\nassert: mock: I don't know what to return because the method call was unexpected.\n\tEither do Mock.On(\"GetByPhone\").Return(...) first, or remove the GetByPhone() call.\n\tThis method was unexpected:\n\t\tGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"7n8c8937d38d73\"}\n\tat: [/home/runner/work/Testing/Testing/internal/storage/mocks/EmployeeStorage.go:69 /home/runner/work/Testing/Testing/internal/service/auth.go:117 /home/runner/work/Testing/Testing/internal/service/auth_test.go:78 /home/runner/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.32/core/common/steps.go:27 /home/runner/work/Testing/Testing/internal/service/auth_test.go:59]","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"\nassert: mock: I don't know what to return because the method call was unexpected.\n\tEither do Mock.On(\"GetByPhone\").Return(...) first, or remove the GetByPhone() call.\n\tThis method was unexpected:\n\t\tGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"7n8c8937d38d73\"}\n\tat: [/home/runner/work/Testing/Testing/internal/storage/mocks/EmployeeStorage.go:69 /home/runner/work/Testing/Testing/internal/service/auth.go:117 /home/runner/work/Testing/Testing/internal/service/auth_test.go:78 /home/runner/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.32/core/common/steps.go:27 /home/runner/work/Testing/Testing/internal/service/auth_test.go:59]","statusTrace":"\n\nassert: mock: I don't know what to return because the method call was unexpected.\n\tEither do Mock.On(\"GetByPhone\").Return(...) first, or remove the GetByPhone() call.\n\tThis method was unexpected:\n\t\tGetByPhone(context.todoCtx,*dto.GetEmployeeRequest)\n\t\t0: context.todoCtx{emptyCtx:context.emptyCtx{}}\n\t\t1: &dto.GetEmployeeRequest{PhoneNumber:\"7n8c8937d38d73\"}\n\tat: [/home/runner/work/Testing/Testing/internal/storage/mocks/EmployeeStorage.go:69 /home/runner/work/Testing/Testing/internal/service/auth.go:117 /home/runner/work/Testing/Testing/internal/service/auth_test.go:78 /home/runner/go/pkg/mod/github.com/ozontech/allure-go/pkg/framework@v0.6.32/core/common/steps.go:27 /home/runner/work/Testing/Testing/internal/service/auth_test.go:59]","steps":[{"name":"Incorrect phone number","time":{"start":1728203504154,"stop":1728203504154,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"ctx","value":"context.TODO"},{"name":"request","value":"&{PhoneNumber:7n8c8937d38d73 Password:21e12}"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":0,"hasContent":true},"afterStages":[],"labels":[{"name":"language","value":"go1.23.1"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"fv-az1759-555"},{"name":"thread","value":"TestRunner/AuthSuite/Test_Auth_LoginEmployee1"},{"name":"suite","value":"AuthSuite"},{"name":"package","value":"course/internal/service_test.TestRunner"},{"name":"tag","value":"auth"},{"name":"tag","value":"login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":["auth","login"]},"source":"4c469ae6f86eb573.json","parameterValues":[]}